repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10  # Use the latest tag from https://github.com/astral-sh/ruff-pre-commit/tags
    hooks:
      - id: ruff-check
      - id: ruff-format
