name: jabs

channels:
  - conda-forge

dependencies:
  - python=3.10
  - h5py=3.9.0
  - markdown2>=2.5.1,<3.0.0
  - numpy=1.25
  # - opencv-python-headless>=4.8.1.78,<5.0.0 # see below
  - pandas=2.1.1
  # - pyside6  # see below
  - scikit-learn=1.3.0
  - shapely >=2.0.1,<3.0.0
  - tabulate >=0.9.0,<1.0.0
  - toml >=0.10.2,<0.11.0
  - xgboost=1.7.6
  - pip
  - pip:
    # QtWebEngine is not available on conda-forge for 6.x.
    # https://github.com/conda-forge/qt-webengine-feedstock/pull/46
    # specified version of opencv-python-headless is not available on conda-forge
    # installing JABS as a Python Package will install versions of Pyside6 and opencv-python-headless s
    # as specified in pyproject.toml from PyPI
    - "--editable=."