lint.select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "D",    # pydocstyle
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "RUF",  # Ruff-specific rules
]
lint.ignore = [
    "D203",  # one-blank-line-before-class (conflicts with D211)
    "D212",  # multi-line-summary-first-line (conflicts with D213)
    "D107",  # missing docstring in __init__
    "D105",  # missing docstring in magic method
    "D100",  # missing module docstring (optional for smaller scripts)
    "E501",  # line too long (handled by formatter)
    "D403",  # ignore doc capitalization
    "D415",  # ignore doc punctuation
]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports in __init__ files
