#!/bin/bash
#SBATCH --job-name=jabs-postprocess
#SBATCH --output=logs/jabs-postprocess_%A_%a.out
#SBATCH --error=logs/jabs-postprocess_%A_%a.err
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#
# Array worker for `jabs-cli postprocess`. Every setting, including the #SBATCH
# values above, is supplied by submit_postprocess.sh at submission time; the
# directives are only a fallback for a bare `sbatch`, which this script rejects
# because it has no manifest to work from.
#
# Do not edit this file to configure a run. Use submit_postprocess.sh options,
# or edit the job env file it writes and resubmit.

# No `set -e`: one failing prediction file must not abandon the rest of the slice.
set -uo pipefail

if [[ -z ${JABS_JOB_ENV:-} ]]; then
    echo "ERROR: JABS_JOB_ENV is not set. Submit this job with submit_postprocess.sh." >&2
    exit 1
fi
if [[ ! -r $JABS_JOB_ENV ]]; then
    echo "ERROR: cannot read job env file: ${JABS_JOB_ENV}" >&2
    exit 1
fi
# shellcheck disable=SC1090
source "$JABS_JOB_ENV"
# shellcheck source=lib/worker_common.sh disable=SC1091
source "${JABS_SLURM_LIB:?JABS_SLURM_LIB not set in ${JABS_JOB_ENV}}/worker_common.sh"

# Postprocess a single prediction file.
postprocess_one() {
    local prediction_file=$1
    local args=(postprocess --config "$JABS_CONFIG")

    if [[ -n ${JABS_BEHAVIOR:-} ]]; then args+=(--behavior "$JABS_BEHAVIOR"); fi
    # Without an output directory the prediction file is updated in place.
    if [[ -n ${JABS_OUT_DIR:-} ]]; then
        args+=(--output "${JABS_OUT_DIR}/$(basename -- "$prediction_file")")
    fi
    args+=(${JABS_EXTRA_ARGS[@]+"${JABS_EXTRA_ARGS[@]}"})
    args+=("$prediction_file")

    jabs-cli "${args[@]}"
}

jabs_worker_main postprocess_one \
    "Config:   ${JABS_CONFIG}" \
    "Behavior: ${JABS_BEHAVIOR:-<all in config>}" \
    "Output:   ${JABS_OUT_DIR:-<in place>}"
