#!/bin/bash
#SBATCH --job-name=jabs-classify
#SBATCH --output=logs/jabs-classify_%A_%a.out
#SBATCH --error=logs/jabs-classify_%A_%a.err
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#
# Array worker for `jabs-classify classify`. Every setting, including the
# #SBATCH values above, is supplied by submit_classify.sh at submission time;
# the directives are only a fallback for a bare `sbatch`, which this script
# rejects because it has no manifest to work from.
#
# Do not edit this file to configure a run. Use submit_classify.sh options, or
# edit the job env file it writes and resubmit.

# No `set -e`: one failing pose file must not abandon the rest of the slice.
set -uo pipefail

if [[ -z ${JABS_JOB_ENV:-} ]]; then
    echo "ERROR: JABS_JOB_ENV is not set. Submit this job with submit_classify.sh." >&2
    exit 1
fi
if [[ ! -r $JABS_JOB_ENV ]]; then
    echo "ERROR: cannot read job env file: ${JABS_JOB_ENV}" >&2
    exit 1
fi
# shellcheck disable=SC1090
source "$JABS_JOB_ENV"
# shellcheck source=lib/worker_common.sh disable=SC1091
source "${JABS_SLURM_LIB:?JABS_SLURM_LIB not set in ${JABS_JOB_ENV}}/worker_common.sh"

# Classify a single pose file.
classify_one() {
    local pose_file=$1
    local args=(classify --input-pose "$pose_file" --out-dir "$JABS_OUT_DIR")

    if [[ -n ${JABS_CLASSIFIER:-} ]]; then
        args+=(--classifier "$JABS_CLASSIFIER")
    else
        args+=(--training "$JABS_TRAINING")
    fi
    if [[ -n ${JABS_FEATURE_DIR:-} ]]; then args+=(--feature-dir "$JABS_FEATURE_DIR"); fi
    if [[ -n ${JABS_FPS:-} ]]; then args+=(--fps "$JABS_FPS"); fi
    if [[ -n ${JABS_USE_POSE_HASH:-} ]]; then args+=(--use-pose-hash); fi
    if [[ -n ${JABS_SKIP_WINDOW_CACHE:-} ]]; then args+=(--skip-window-cache); fi
    args+=(${JABS_EXTRA_ARGS[@]+"${JABS_EXTRA_ARGS[@]}"})

    jabs-classify "${args[@]}"
}

jabs_worker_main classify_one \
    "Classifier: ${JABS_CLASSIFIER:-${JABS_TRAINING} (training file)}" \
    "Output:   ${JABS_OUT_DIR}"
